# Generated by Django 5.0.4 on 2024-12-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_cars', models.AutoField(primary_key=True, serialize=False)),
                ('cars_name', models.CharField(max_length=50)),
                ('warna', models.CharField(max_length=50)),
                ('tahun', models.IntegerField()),
                ('CC', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
    ]
