# Generated by Django 5.0.4 on 2024-12-03 18:45

import CarDealer.cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(default=1, upload_to='images', validators=[CarDealer.cars.validators.validate_file_size]),
            preserve_default=False,
        ),
    ]
