# Generated by Django 5.0.4 on 2024-12-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_cars_category'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='category',
        ),
        migrations.AddField(
            model_name='cars',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
            preserve_default=False,
        ),
    ]
