# Generated by Django 5.0.4 on 2024-12-03 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_cars_category_cars_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='categories',
            new_name='category',
        ),
    ]
