# Generated by Django 5.0.4 on 2024-12-09 17:13

import CarDealer.cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_categories_cars_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[CarDealer.cars.validators.validate_file_size]),
        ),
    ]
