# Generated by Django 5.0.4 on 2024-12-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_testdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='test_drive_date',
            field=models.DateField(),
        ),
    ]
